config/routes.rb
Rails.application.routes.draw do
  resources :users_overview
  resources :tasks
  devise_for :users, :controllers => {:registrations => "registrations"}
  namespace :api do
    namespace :v1 do
      match 'sessions' => 'sessions#destroy_my', :via => :delete
      resources :sessions
      resources :tasks
      resource :comments
    end
  end

  post "tasks/:id/comment", to: 'comments#create'
  get "comment/:id", to: 'comments#edit'
  put "comment/:id", to: 'comments#update'

  root to: 'tasks#index'

end

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= nav_link 'Tasks', tasks_path %>
        <%= nav_link 'Users', '/users_overview' %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <%= nav_link 'Logout', destroy_user_session_path, :delete %>
            <%= nav_link current_user.web_name, edit_user_registration_path %>
        <% else %>
            <%= nav_link 'Login', new_user_session_path %>
            <%= nav_link 'Register', new_user_registration_path %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>