config/routes.rb
Rails.application.routes.draw do
  resources :users_overview
  resources :tasks
  devise_for :users, :controllers => {:registrations => "registrations"}
  namespace :api do
    namespace :v1 do
      match 'sessions' => 'sessions#destroy_my', :via => :delete
      resources :sessions
      resources :tasks
      resource :comments
    end
  end

  post "tasks/:id/comment", to: 'comments#create'
  get "comment/:id", to: 'comments#edit'
  put "comment/:id", to: 'comments#update'

  root to: 'tasks#index'

end

app/controllers/users_overview_controller.rb
class UsersOverviewController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    set_users
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.company = current_user.company
    @user.add_role :worker

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_overview_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_overview_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    set_users
    respond_to do |format|
      format.html { redirect_to '/users_overview', notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find_by(id: params[:id], company: current_user.company)
  end

  def set_users
    @users = User.where(company: current_user.company).where.not(id: current_user.id)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation)
  end
end

app/helpers/users_overview_helper.rb
module UsersOverviewHelper
end

app/views/users_overview/_form.html.slim
- @user.id == nil ? action = 'create' : action = 'update'
= form_for @user, :url => url_for(:controller => 'users_overview', :action => action) do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :email
    = f.email_field :email

  = f.fields_for :role do |ff|
      .checkbox-inline
        = ff.label :manager
        = ff.check_box :manager
      /hidden_field_tag(role, 0)
      /check_box_tag(role, 1, @user.has_role?(role))
      .checkbox-inline
        = ff.label :worker
        = ff.check_box :worker

  /<% @roles.each do | role | %>
  /  <%= f.label(role) do %>
  /    role.name
  /    <%= hidden_field_tag(role, 0) %>
  /    <%= check_box_tag(role, 1, @user.has_role?(role)) %>
  /  <% end %>
  /  <% end %>
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions = f.submit

app/views/users_overview/edit.html.slim
h1 Editing user

== render 'form'

app/views/users_overview/index.html.slim
table class='table-hover table'
  thead
    tr
      th Name
      th Surname
      th Email
      th Role

  tbody data-link='row' class='rowlink'
    - @users.each do |user|
      tr
        td
          a href = users_overview_path(user)
            = user.name
        td = user.surname
        td = user.email
        - role_names = ''
        - user.roles.each { |role| role_names << role.name
        -   role != user.roles.last ? role_names << ', ' : ''
        - }
        td = role_names
br

= link_to 'New User', new_users_overview_path

app/views/users_overview/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', :back

app/views/users_overview/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Surname:
  = @user.surname
p
  strong Email:
  = @user.email

= link_to 'Edit', edit_users_overview_path(@user)
'|
= link_to 'Destroy', users_overview_path(@user), data: {:confirm => 'Are you sure? All the tasks assigned to this user will be destroyed as well!'}, :method => :delete